### ISSUE TITLE
[TASK] - Security Features

### ISSUE THREAD

**Issue by tcsresearch** [tcsresearch/tarmonster#17]
```[tasklist]
### Security Features For TarMonster
- [ ] Enable Encrypted Bacups and Restores. <a href="https://github.com/tcsresearch/tarmonster/issues/16"> #16 </a>
- [ ] TarMonster Should Test Restores Prior To Finalizing. <a href="TarMonster Should Test Restores Prior To Finalizing."> #15 </a>
- [ ] Enable Checksumming Option For Backups and Restores. <a href="https://github.com/tcsresearch/tarmonster/issues/14"> #14 </a>
```
